steps:
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['set', 'image', 'deployment/mydepl', 'my-image=gcr.io/my-project/myimage']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=my-clusters'
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/my-project-id/myimage', '.']
steps:
- name: python
  entrypoint: python
  args: ["-m", "pip", "install", "--upgrade", "pip"]
- name: python
  entrypoint: python
  args: ["-m", "pip", "install", "build", "pytest", "Flask", "--user"]
